name: Consumer Workflow

on:
  push:
    branches:
      - main


jobs:
  call_greeting:
    uses: ugale-deepak3010/Deep-Git-Composite-Action/.github/workflows/display-name.yml@main
    with:
      name: "Deepak"
