name: Consumer Workflow

on:
  push:
    branches:
      - main

jobs:
  call_greeting:
    uses: ugale-deepak3010/template-repo/.github/workflows/greeting-template.yml@main
    with:
      name: "Deepak"
