name: Consumer Workflow

on:
  push:
    branches:
      - main


jobs:
  call_greeting:
    #uses: ugale-deepak3010/Deep-Git-Composite-Action/.github/workflows/display-name/action.yml@main
    uses: ugale-deepak3010/Deep-Git-Composite-Action/.github/workflows/display-name.yml@main
    with:
      name: "De--1-epak"
      script_path: "./src/addition.py"
