name: Consumer Workflow

on:
  push:
    branches:
      - main

jobs:
  call_greeting:
  
    uses: ugale-deepak3010/Deep-Git-ReUsable-Action/.github/workflows/BuildAndPublishDockerImg.yml@v1
    with:
      name: "De--2--epak"
      script_path: "./src/addition.py"
    secrets:
      password: "Pass123"


