name: My First actions
#can be push or pull or both.
on: [push] 

env:
  version: 9.16.0
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]
    #stages
    steps:

    #uses in actions/checkout is hardcoded and it referring from marketplace. 
    #here is the docs url https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-maven#specifying-the-java-version-and-architecture
    - uses: actions/checkout@v3
    - name: Setup python

    #installing python help of actions from referring this marketplace.
    # @v2 referring plugin version not python version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Displaying Number
      run: |
        echo "Building version= ${{env.version}}${{ github.run_number }}"

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
      
          


